packages:
  - apps/*
  - packages/*

exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.next/**'
  - '**/.turbo/**'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - dtrace-provider
  - esbuild
  - sharp
